server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:./data/nutritrack;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

app:
  jwt:
    issuer: nutritrack
    secret: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET_AT_LEAST_32_CHARS"
    accessTokenMinutes: 60

# springdoc-openapi (Swagger UI + /v3/api-docs)
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    enabled: true
  show-actuator: false

